@startuml

!theme sandstone


start
repeat 
repeat :Get animal details;
' if(Request unsuccessful?) then (yes)

' endif
repeat while (Non-successful request\nand less than 3 tries)

if (Still not successful?) then (yes)
:Break the circuit;
:Wait for the circuit to open;
else (no, data received)
	:Print animal details;
	stop
endif
repeat while (Circuit broke 3 times?)
->yes;
:Exception or fallback,\nsomething is really wrong;
stop

@enduml

