@startuml

!theme bluegray

start

:Plan onderhoudsbeurt in;

while(Succes?) is (nee)
	if(Internal Server Error) then (ja)
		:Opslaan in wachtrij;
		stop
	elseif (Too Many Requests) then (ja)
		:Verbreek het circuit;
		:Wacht 30 seconden;
	else (nee)
	endif
	backward: Nogmaals proberen;
endwhile
-> ja;
:Verwerk reservering;

stop

@enduml